/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatUI: typeof import('./components/ChatUI.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    JsonEditor: typeof import('./components/JsonEditor.vue')['default']
  }
}
